### ISSUE TITLE
comments on the Singularity contents 

### ISSUE THREAD

**Issue by jianlianggao** [aturner-epcc/containers-workshop#15]
in https://aturner-epcc.github.io/containers-workshop/09-singularity-gettingstarted/index.html
1.	If use the term “episodes” , maybe good to use episode 1: episode 2 …
2.	Maybe better to have installation of singularity in the get started section?
in https://aturner-epcc.github.io/containers-workshop/12-singularity-mpi/index.html
1.	Need a line of how to build Singularity image from the example .def file;  for example,  sudo singularity build osu_benchmarks.sif osu_benchmarks.def   (need sudo permission to do)

**Comment by aturner-epcc** [comment]
Thanks @jianlianggao .

I will have a look at the episodes terminology - you are right we should be explicit about what episodes we are referring to. 

Yes, Singularity instructions in the setup page would be useful and I will add something - however, note that the planned way to use Singularity to build is to use the Singularity Docker image so there should be no need to install Singularity on their local systems.

We will check the instructions. We plan to use the Docker Singularity container to build images so the command does not need sudo (I do not think) as you are already root in the Docker container.

**Comment by jianlianggao** [comment]
You're welcome Andy. If users run in the Dockerized Singularity container, then it should be fine. It's good to get rid of the hassle of installing singularity. I just tried on my Ubuntu 20.04, it requried quite a few dependencies and complier Go to install from source.

**Comment by jcohen02** [comment]
I realise this has been closed but thanks for highlighting this @jianlianggao and just to point out that there is a comment in the [Singularity: Getting Started](https://imperialcollegelondon.github.io/2020-07-13-Containers-Online/09-singularity-gettingstarted/index.html) episode about installing on your own machine. We originally had this in the main setup section but I decided to move it since I felt it complicated things to start highlighting advanced Singularity tasks right at the start of the course before people had even got started with Docker.

Once we decided that we'd be using the Singularity Docker container anyway, because people on Windows (and to some extent, Mac too*) wouldn't be able to install natively, the information about installing Singularity yourself became more of an advanced option. We wanted to highlight this but since it isn't so critical any more, I thought it should fit OK into the Getting Started section of the Singularity material. Happy to move this material about installing Singularity if you feel it fits better somewhere else.

*there is now [Singularity Desktop MacOS](https://sylabs.io/singularity-desktop-macos/) in beta
